quarkus:
  rest-client:
    de.schulte.smartbar.orderclient.login.MenuApiClient:
      url: "http://localhost:8088"
  cache:
    caffeine:
      expire-after-write: 10S
  redis:
    logins:
      hosts: redis://localhost:5200/0
